### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by mrbluecoat** [sssxyd/go-sse-broker#2]
Recommended to add https://github.com/gin-gonic/autotls to https://github.com/sssxyd/go-sse-broker/blob/main/main.go#L15 to support TLS

**Comment by sssxyd** [comment]
This is not a service that should be exposed directly to the Internet. When using it, it should be used through nginx/openresty reverse proxy and provide support for SSL and gzip.

**Comment by mrbluecoat** [comment]
I see, similar to https://nchan.io then. Thanks.
